### ISSUE TITLE
[v2] Issues with Laravel's storage locations

### ISSUE THREAD

**Issue by aran112000** [brefphp/laravel-bridge#101]
We're having some issues with Laravel's default storage location if `php artisan optimize:clear` is run prior to deployment - it seems Laravel's still insisting on these dirs being there, even if they're not used as they've been remapped!

```bash
Running 'php artisan config:cache' to cache the Laravel configuration In StreamHandler.php line 197:
There is no existing directory at "/var/task/storage/logs" and it could not be created: Read-only file system

The /var/task/bootstrap/cache directory must be present and writable.

Running 'php artisan config:cache' to cache the Laravel configuration In StreamHandler.php line 197:
There is no existing directory at "/var/task/storage/logs" and it could not be created: Read-only file system

The /var/task/bootstrap/cache directory must be present and writable.
```

**Comment by tillkruss** [comment]
You don't need to run `php artisan optimize`, since nothing's there to clear IMO.

**Comment by aran112000** [comment]
We've been having some strange issues with Laravel Debugbar not showing (still trying to get to the bottom of why!) when the config caches have been built on Lambda for some reason which is what's forced us to have to completely clear the caches
