### ISSUE TITLE
Bump to L8

### ISSUE THREAD

**Issue by rmundel** [brefphp/laravel-bridge#11]
Any plans to upgrade the dependencies to support Laravel 8 anytime soon?

**Comment by mnapoli** [comment]
I have not followed Laravel 8 closely, but from what I've read I didn't any major change that could impact us here. Might be worth giving it a try and reporting back.

**Comment by daanpeer** [comment]
I've created an MR to update the `illuminate/*` dependencies #13. For me it caused some issues while running Composer.
