### ISSUE TITLE
Compatibility with Octane 2.x

### ISSUE THREAD

**Issue by natanparmigianoreis** [brefphp/laravel-bridge#132]
Currrently the package is marked as compatible with octane 1.2 explicitly, which makes any Laravel 10.x (which is only compatible with octane 2.x) instalation fall back to bref/laravel-bridge:^1.2 , since that is the last version that does not include the octane requirement in its dependencies.

If nothing "breaks" with the new octane version, it should be a simple version bump.

**Comment by natanparmigianoreis** [comment]
Just forked the package and tried it out on a relatively simple application and it seems a simple version bump caused no immediately obvious issues, it surely needs more through testing but right now it seems that it works alright.

https://github.com/natanparmigianoreis/laravel-bridge/blob/master/composer.json

**Comment by mnapoli** [comment]
That's awesome, thanks for testing. Would you be able to send a pull request?
