### ISSUE TITLE
Unable to process SQS events

### ISSUE THREAD

**Issue by hesomApptega** [brefphp/laravel-bridge#15]
Using Laravel 7 and the php 7.4 layer. 

I have setup a worker.php and made the changes to the serverless.yml file. I am able to write to the SQS queue, but when the lambda tries to process the event, I am seeing this error message:

This handler expected to be invoked with a API Gateway or ALB event. Instead, the handler was invoked with invalid event data.

 "stack": [
        "#0 /var/task/vendor/bref/bref/src/Event/Http/HttpHandler.php(20): Bref\\Event\\Http\\HttpRequestEvent->__construct()",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(107): Bref\\Event\\Http\\HttpHandler->handle()",
        "#2 /opt/bootstrap(35): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#3 {main}"
    ]

It seems to me that the API handler is trying to process the event, not the SQS handler.

**Comment by mnapoli** [comment]
Yes, you most likely have an error in your serverless.yml. It's not possible to help further without more details, feel free to share.

**Comment by hesomApptega** [comment]
@mnapoli 

Here is what I have in my yml file
<img width="965" alt="Screen Shot 2020-10-03 at 1 27 59 PM" src="https://user-images.githubusercontent.com/56939508/94997925-59773400-057c-11eb-9288-b336b20d15b0.png">

I created the SQS manually and placed the ARN in there. The lambda trigger successfully attaches to the queue, it almost looks like the bridge does not pick it up, the other router does. 

In the error message above, I can see the entire queue item that it's trying to process. 

I am testing using queue able emails.

**Comment by mnapoli** [comment]
The `worker` function should not have the `-fpm` runtime, it should run with the `php-74` (function) runtime instead. You can find a full example in the readme.
