### ISSUE TITLE
Default Laravel 11 installation crashes with database session

### ISSUE THREAD

**Issue by deleugpn** [brefphp/laravel-bridge#160]
Laravel 11 uses `database` as the default `session` driver and it also uses `sqlite` as the default database engine. This makes Bref configuration not take effect by default (https://github.com/brefphp/laravel-bridge/blob/master/src/BrefServiceProvider.php#L141-L143) and also fails because SQLite location is not writeable.

**Comment by mnapoli** [comment]
https://github.com/brefphp/laravel-bridge/pull/161
