### ISSUE TITLE
Using `failed_jobs` table instaed of dead-letter queue

### ISSUE THREAD

**Issue by georgeboot** [brefphp/laravel-bridge#22]
This package currently uses a dead-letter queue for failed jobs. This might be more in line with industry standards, but it's a bit different from "the Laravel way".

How hard would it be to use Larvels `failed_jobs` table instead, so I can easily call `artisan job:retry 5`?

Also, it seems that the attempts count (`$job->tries`) doesn't work (https://github.com/brefphp/laravel-bridge/issues/14). This also messes a bit with the default Laravel setup.

Any thoughts?

**Comment by mnapoli** [comment]
Fixed by https://github.com/brefphp/laravel-bridge/pull/94 😄
