### ISSUE TITLE
Bref bref/laravel-bridge conflicts with bref/bref ~0.5.20

### ISSUE THREAD

**Issue by reksmeysrey** [brefphp/laravel-bridge#25]
![image](https://user-images.githubusercontent.com/35394133/100349742-81829100-301b-11eb-826f-aca56044d43d.png)

I saw in bref/laravel-bridge composer.json still `bref/bref ~0.5.20` not compatible 
How to solve it?

**Comment by marcusmyers** [comment]
This should be solved with [this](https://github.com/brefphp/laravel-bridge/pull/24) pull request.

**Comment by mnapoli** [comment]
I've released a new version: https://github.com/brefphp/laravel-bridge/releases/tag/1.0.0
