### ISSUE TITLE
Different lamda confirguration for some jobs

### ISSUE THREAD

**Issue by Salmondx** [brefphp/laravel-bridge#29]
Hi! Is it possible to have several SQS queues and connections and map them to different lamda instances using bref?

For example, I have regular queue tasks that can be processed on 1gb lambda instance, and a cpu intensive tasks that requires a 5-10gb lamda instance. Currently I have several servers and map tasks between them using different ‘artisan queue:work —connection={name}’ workers.

Is it something that bref/serverless can handle?

**Comment by mnapoli** [comment]
Hi, yes that is definitely possible with Bref.

FYI feel free to chat and ask for support in the GitHub discussions of Bref: https://github.com/brefphp/bref/discussions/categories/support

**Comment by mnapoli** [comment]
And sorry for the delay, with the holidays :)
