### ISSUE TITLE
Errors occur during runtime when `bootstrap/cache` has `routes.php` or misses `packages.php` and `services.php`

### ISSUE THREAD

**Issue by pjxiao** [brefphp/laravel-bridge#37]
## The problem

* a. When I deplyed my codes where `boostrap/cache` directory has `routes.php` (along with `packages.php` and `services.php`), the deployed lambda function failed because the route cache has an invalid format.
* b. When I deplyed my codes where `boostrap/cache` directory has `packages.php` and `services.php`, the deployed lambda function failed because the cache directory is absent or isn't present.

## Questions

* a. Should I exlude `routes.php` from a deployment package?
* b1. Should I include `packages.php` and `services.php`?
* b2. Is it safe to deploy locally generated `packages.php` and `services.php` to Lambda? (In other words, do those caches not depned on an environment where they were generated?)

## An environment

* php: `bref:layer.php-73`
* Laravel: 6.20.7
* laravel-bridge: 1.0.0

### a. when `bootstrap/cache` has `routes.cache`

```
START RequestId: ****-****-****-****-**** Version: $LATEST
Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute'
END RequestId: ****-****-****-****-****
REPORT RequestId: ****-****-****-****-****	Duration: 102.57 ms	Billed Duration: 103 ms	Memory Size: 512 MB	Max Memory Used: 17 MB	
Unknown application error occurred
```

### b. when `bootstrap/cache` is empty

```
The /var/task/bootstrap/cache directory must be present and writable.
START RequestId: ****-****-****-****-**** Version: $LATEST
The /var/task/bootstrap/cache directory must be present and writable.
END RequestId:  ****-****-****-****-****
REPORT RequestId:  ****-****-****-****-****	Duration: 100.26 ms	Billed Duration: 101 ms	Memory Size: 512 MB	Max Memory Used: 14 MB	
Unknown application error occurred
```

**Comment by francoisauclair911** [comment]
Did you ever find a solution ?

**Comment by mnapoli** [comment]
What I don't understand with this issue is how does that situation happen?

When following the official documentation is there any problem?

**Comment by pjxiao** [comment]
Sorry, I've left the team where bref was used, and I've forgotten the problem details. They may have used an older version. So I'll close this issue. I appreciate your replies.
