### ISSUE TITLE
Job processed but lambda function time out

### ISSUE THREAD

**Issue by otezz** [brefphp/laravel-bridge#46]
Hi,

I create a test app for this package on https://github.com/otezz/test-bref-queue. I can see jobs from laravel are processed and record inserted to RDS successfully, but it seems that the job not quitting immediately and idling until the lambda function time out causing the task marked as failed.

Is there something wrong with my configurations?

**Comment by deleugpn** [comment]
Do you see the log line on CloudWatch as well?

**Comment by otezz** [comment]
Yes, I can see the log line

Here's screenshot from cloudwatch
![image](https://user-images.githubusercontent.com/2015833/123820088-80547200-d924-11eb-95c7-9d5646e726ef.png)

The task run 3 times before moved to dead-letter

**Comment by deleugpn** [comment]
Maybe you can try to increase the timeout to see if it solves it (by just giving a bit more time). Timeout are common when your Lambda is in a VPC without NAT Gateway because you lose access to the internet. However, I don't detect any reason why your project would be trying to connect to the internet

**Comment by otezz** [comment]
I've increased the timeout to 120s but still timed out

![image](https://user-images.githubusercontent.com/2015833/123825488-25714980-d929-11eb-992b-f85516e83d41.png)

Is it possible to install new relic's apm to the app to see which function taking too long?

**Comment by otezz** [comment]
So I managed to make it work by deploying worker in other VPC that have NAT gateway in it. I'm not sure why I need NAT gateway since my function doesn't need to connect to the internet

![image](https://user-images.githubusercontent.com/2015833/123921704-804e8380-d9b1-11eb-907d-6723bff7fb27.png)
