### ISSUE TITLE
Example to migrate Horizon

### ISSUE THREAD

**Issue by billkidwell** [brefphp/laravel-bridge#5]
I have just discovered the BREF package (via Serverless Chats Podcast) and I am very interested in trying it out.  One of my pain points in my AWS deployment is my queue workers.  I would love to move those to Lambda.

The application currently uses Laravel Horizon.  I am not familiar enough with the underpinnings of horizon to apply the given documentation to a Horizon context.  An example, or some documentation on converting Horizon to use this package would be a welcome addition.

**Comment by mnapoli** [comment]
Hi! Laravel Horizon unfortunately targets Redis only, and using Lambda would make sense only with SQS.

Switching from Redis to SQS is fairly easy, however you would loose the Horizon dashboard :/

(unless I missed a way to use Horizon with SQS)

**Comment by billkidwell** [comment]
Ah, I missed this.  The former developers used SQS in the past, but must have added horizon after they switched to Redis.  

That may delay my interest, but it sounds like a safe migration path is, remove Horizon and move to Laravel Queue Workers, then switch to SQS, then switch to serverless workers.  

I'll do some research on SQS dashboards that might fill the Horizon dashboard function.  Feel free to close the issue.  I can now see why this is out of scope.

**Comment by mnapoli** [comment]
👍 

FYI it is possible to create some dashboards with AWS CloudWatch, but it requires a bit of effort, and there are not as nice as Horizon.

This is a topic I want to work on (to provide useful dashboards with SQS).
