### ISSUE TITLE
Cannot parse "serverless.yml": unknown tag !<!node_modules/**>

### ISSUE THREAD

**Issue by HELMAB** [brefphp/laravel-bridge#57]
I'm running Laravel 8, Bref 1.3 and Laravel-Bridge 1.1

When I run `serverless deploy`

I got this error:

Cannot parse "serverless.yml": unknown tag !<!node_modules/**> in "/Users/aws/Desktop/laravel-aws-lambda/serverless.yml" (16:9)
  
   13 |     # Directories to exclude from deplo ...
   14 |     patterns:
   15 |         - !node_modules/**
   16 |         - !public/storage
  --------------^
   17 |         - !resources/assets/**
   18 |         - !storage/**

Does anybody face this problem?

**Comment by t-richard** [comment]
It's indeed linked to this change :roll_eyes: 

I've opened #58 to fix it.

In the meantime, @HELMAB you can change your `serverless.yml` accordingly :slightly_smiling_face:
