### ISSUE TITLE
Lumen Settings lambda

### ISSUE THREAD

**Issue by cemarta7** [brefphp/laravel-bridge#7]
Hello
I keep getting this.
"#0 /var/task/vendor/illuminate/database/Eloquent/Model.php(1223): Illuminate\\Database\\Eloquent\\Model::resolveConnection(NULL)",
        "#1 /var/task/vendor/illuminate/database/Eloquent/Model.php(1052): Illuminate\\Database\\Eloquent\\Model->getConnection()",
        "#2 /var/task/vendor/illuminate/database/Eloquent/Model.php(969): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()",
        "#3 /var/task/vendor/illuminate/database/Eloquent/Model.php(1005): Illuminate\\Database\\Eloquent\\Model->newModelQuery()",
        "#4 /var/task/vendor/illuminate/database/Eloquent/Model.php(958): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()",
        "#5 /var/task/vendor/illuminate/database/Eloquent/Model.php(1622): Illuminate\\Database\\Eloquent\\Model->newQuery()",
        "#6 /var/task/vendor/illuminate/database/Eloquent/Model.php(1634): Illuminate\\Database\\Eloquent\\Model->__call('create', Array)",

Interesting when the request comes from web the connection to the db has no issues regular bref. But while doing it with lambda I get this error. I did added the security groups as defined on https://bref.sh/docs/environment/database.html

I had to remove this like from the worker in order for it to work.
//$kernel->bootstrap();

Could this be also because this is a lumen project not a full laravel version?

maybe something is not loading?

**Comment by mnapoli** [comment]
Hi, you added the stack trace of the error but not the exception itself (the class name and message). I can't really help further without it.

**Comment by cemarta7** [comment]
My bad this is the full error stack.

"errorType": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "errorMessage": "Call to a member function connection() on null",
    "stack": [
        "#0 /var/task/vendor/illuminate/database/Eloquent/Model.php(1223): Illuminate\\Database\\Eloquent\\Model::resolveConnection(NULL)",
        "#1 /var/task/vendor/illuminate/database/Eloquent/Model.php(1052): Illuminate\\Database\\Eloquent\\Model->getConnection()",
        "#2 /var/task/vendor/illuminate/database/Eloquent/Model.php(969): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()",
        "#3 /var/task/vendor/illuminate/database/Eloquent/Model.php(1005): Illuminate\\Database\\Eloquent\\Model->newModelQuery()",
        "#4 /var/task/vendor/illuminate/database/Eloquent/Model.php(958): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()",
        "#5 /var/task/vendor/illuminate/database/Eloquent/Model.php(1622): Illuminate\\Database\\Eloquent\\Model->newQuery()",
        "#6 /var/task/vendor/illuminate/database/Eloquent/Model.php(1634): Illuminate\\Database\\Eloquent\\Model->__call('create', Array)",
        "#7 /var/task/app/Repositories/PushNotificationsRepository.php(75): Illuminate\\Database\\Eloquent\\Model::__callStatic('create', Array)",
        "#8 /var/task/app/Jobs/ProcessPushMealDeliveryJob.php(40): App\\Repositories\\PushNotificationsRepository::recordPushNotification(69930, 'Hi Gerardo. You...', '')",
        "#9 [internal function]: App\\Jobs\\ProcessPushMealDeliveryJob->handle()",
        "#10 /var/task/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array(Array, Array)",
        "#11 /var/task/vendor/illuminate/container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()",
        "#12 /var/task/vendor/illuminate/container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))",
        "#13 /var/task/vendor/illuminate/container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))",
        "#14 /var/task/vendor/illuminate/container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)",
        "#15 /var/task/vendor/illuminate/bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)",
        "#16 /var/task/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\ProcessPushMealDeliveryJob))",
        "#17 /var/task/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ProcessPushMealDeliveryJob))",
        "#18 /var/task/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
        "#19 /var/task/vendor/illuminate/queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\ProcessPushMealDeliveryJob), false)",
        "#20 /var/task/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\ProcessPushMealDeliveryJob))",
        "#21 /var/task/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ProcessPushMealDeliveryJob))",
        "#22 /var/task/vendor/illuminate/queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
        "#23 /var/task/vendor/illuminate/queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SqsJob), Object(App\\Jobs\\ProcessPushMealDeliveryJob))",
        "#24 /var/task/vendor/illuminate/queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SqsJob), Array)",
        "#25 /var/task/vendor/bref/laravel-bridge/src/Queue/LaravelSqsHandler.php(87): Illuminate\\Queue\\Jobs\\Job->fire()",
        "#26 /var/task/vendor/bref/laravel-bridge/src/Queue/LaravelSqsHandler.php(69): Bref\\LaravelBridge\\Queue\\LaravelSqsHandler->process('sqs', Object(Illuminate\\Queue\\Jobs\\SqsJob))",
        "#27 /var/task/vendor/bref/bref/src/Event/Sqs/SqsHandler.php(18): Bref\\LaravelBridge\\Queue\\LaravelSqsHandler->handleSqs(Object(Bref\\Event\\Sqs\\SqsEvent), Object(Bref\\Context\\Context))",
        "#28 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(106): Bref\\Event\\Sqs\\SqsHandler->handle(Array, Object(Bref\\Context\\Context))",
        "#29 /opt/bref/bootstrap.php(38): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Bref\\LaravelBridge\\Queue\\LaravelSqsHandler))",
        "#30 {main}"
    ]
}

I am moving the project to a Laravel instead of Lumen. I wonder if that could be the issue.

**Comment by cemarta7** [comment]
I fixed it. The issue is that the worker.php was referencing Laravel

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

But I in Lumen it has to be

$app->make(Laravel\Lumen\Console\Kernel::class);
$app->boot();

Hope this helps others.
