### ISSUE TITLE
[Solution] No such file or directory, touch() or mkdir().

### ISSUE THREAD

**Issue by mariuszmalek** [brefphp/laravel-bridge#75]
If you have a problem with storage in Lambda, then I believe this solution is for you. Please check your logs and try to find any of these **problems** if you have this then try to do what is in this issue: 

> "touch(): Unable to create file", "mkdir()", "No such file or directory"

I used spatie media-library in my project, and I had a problem with storage media in /tmp, but for a long time I found a solution for that.

Solution for that is to install **extra-php-extensions** and update config file

![unknown](https://user-images.githubusercontent.com/26696860/186413014-8d1373a2-d205-4442-a969-5436193ca182.png)

After that, you should update app.php file in bootstrap

![unknown (1)](https://user-images.githubusercontent.com/26696860/186413093-68493932-31e2-49e8-a89c-8d4610184cc4.png)

Now everything should work fine :)

**Comment by mnapoli** [comment]
Will be fixed by https://github.com/brefphp/laravel-bridge/pull/94
