### ISSUE TITLE
Missing override path for "real-time" facades

### ISSUE THREAD

**Issue by yangm97** [brefphp/laravel-bridge#8]
```
file_put_contents(/var/task/storage/framework/cache/facade-d6c8a1ed6fde286ae195e535517be856b15c1f39.php): failed to open stream: No such file or directory
```

**Comment by mnapoli** [comment]
Hi, have you tried upgrading to the latest version?

In the last version, I moved the cache directory in `/tmp`, which should solve the problem with all cache directories.

**Comment by yangm97** [comment]
Unfortunately it seems like the facade cache doesn't make use of the cache directory setting and makes raw calls to `storage_path()` as seen [here](https://github.com/laravel/framework/blob/c2f2867cb1c835fd32c91bc9a772c3ec1ce68894/src/Illuminate/Foundation/AliasLoader.php#L103) and [here](https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Cache/Console/ClearCommand.php#L89).

Do you think this needs to be fixed upstream instead?

**Comment by mnapoli** [comment]
I would think so yes (fix upstream) but it doesn't look like it will. I'm not sure what we can do though 🤔

**Comment by yangm97** [comment]
I've been meditating about this issue and it really looks like we can't do anything other than their proposed workaround if we want real time facades working on Bref 😔

Do you think it's better for me to polish that PR or do you have something different in mind?

**Comment by hesomApptega** [comment]
@yangm97 I ran into the same issue, I ended up overriding AliasLoader.php and forcing it to use the tmp directory.

**Comment by tripper54** [comment]
Maybe another option would be to mount an EFS volume for the storage directory:
https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/

**Comment by eneskaya** [comment]
Hi everybody,

I managed to fix this by following what Taylor said on the linked Issue above https://github.com/laravel/framework/issues/33839#issuecomment-673118699

> Vapor takes care of this by tweaking the storage path environment variables I believe.



When we add this code to the `register` method of the `BrefServiceProvider.php`

```php
...
if (! is_dir('/tmp/storage/framework/cache')) {
    mkdir('/tmp/storage/framework/cache', 0755, true)
}

$this->app->useStoragePath('/tmp/storage')
```

everything works fine. I can open a PR here, but I'm uncertain with 

1. wether it is safe to use the `useStoragePath` method on the `Illumniate\Foundation\Application` instance, as it is not exposed in the contract (`Illuminate\Contracts\Foundation\Application`)
2. wether this code belongs in the `register` or the `boot` method 🤔 

[`Illumniate\Foundation\Application` class] https://github.com/laravel/framework/blob/994dbac5c6da856c77c81a411cff5b7d31519ca8/src/Illuminate/Foundation/Application.php

**Comment by mnapoli** [comment]
@tripper54 I wouldn't recommend EFS. From my tests it is much slower, it also requires a VPC and heavy setup with base costs. It's really good as a last resort solution.

**Comment by Mesuva** [comment]
I've hit this issue myself trying to get Livewire file uploads working.
Livewire appears to be loading up some real-time facades, and those then try to be cached in /var/task/storage/framework/cache, as per the original issue described here.

My solution so far feels a bit hacky, but does work:

- I've created my own Application class, extending \Illuminate\Foundation\Application
- in bootstrap/app.php, I load my own class here to create $app:

```
$app = new App\Overrides\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

```
- then in my custom Application class, I've overridden just the storagePath function, putting in a check for running on lambda, and then have it return just /tmp/ as the path if it's trying to write to framework/cache:

<?php

namespace App\Overrides;

```
class Application extends \Illuminate\Foundation\Application
{
    public function storagePath($path = '')
    {
        $isRunningInLambda = isset($_SERVER['LAMBDA_TASK_ROOT']);

        if ($isRunningInLambda && strpos($path, 'framework/cache/') === 0 ) {
            $path = str_replace('framework/cache/', '', $path);
            return '/tmp/' . $path;
        }

        return ($this->storagePath ?: $this->basePath.DIRECTORY_SEPARATOR.'storage')
            .($path != '' ? DIRECTORY_SEPARATOR.$path : '');
    }
}
```

I'm sure there are better ways to achieve this, but this at least feels predicable.

**Comment by josegustavo** [comment]
My solution was:

In bootstrap/app.php

`$app->useStoragePath($_ENV['APP_STORAGE'] ?? (base_path() . '/storage'));`

in .env

`APP_STORAGE=/tmp/storage`

in app/Providers/AppServiceProvider.php

```
public function boot()
{
        $storagePath = config('cache.stores.file.path', '');
        // Make sure the directory for local storage exists
        if (! is_dir($storagePath)) {
            mkdir($storagePath, 0755, true);
        }
}
```

**Comment by mnapoli** [comment]
Will be solved in v2, see https://github.com/brefphp/laravel-bridge/pull/94
